name: wf0

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Read buildversion
      id: buildversion
      uses: juliangruber/read-file-action@v1
      with:
        path: ./version/buildversion

    - name: Echo buildversion
      run: echo "${{ steps.buildversion.outputs.content }}"

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.WORKFLOW_PUBLIC_REPO_PAT }}
        repository: blake256/nightly-test
        event-type: nightly-build-event
        client-payload: '{"branch": "master", "tag": "${{ steps.buildversion.outputs.content }}"}'
